/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as StoreBookingsRouteImport } from './routes/store/bookings'
import { Route as StoreDashboardRouteImport } from './routes/store/dashboard'
import { Route as StoreProductsRouteImport } from './routes/store/products'
import { Route as StoreProfileRouteImport } from './routes/store/profile'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreBookingsRoute = StoreBookingsRouteImport.update({
  id: '/store/bookings',
  path: '/store/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreDashboardRoute = StoreDashboardRouteImport.update({
  id: '/store/dashboard',
  path: '/store/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreProductsRoute = StoreProductsRouteImport.update({
  id: '/store/products',
  path: '/store/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreProfileRoute = StoreProfileRouteImport.update({
  id: '/store/profile',
  path: '/store/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/terms': typeof TermsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/store/bookings': typeof StoreBookingsRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/store/products': typeof StoreProductsRoute
  '/store/profile': typeof StoreProfileRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/products/': typeof ProductsIndexRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/terms': typeof TermsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/store/bookings': typeof StoreBookingsRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/store/products': typeof StoreProductsRoute
  '/store/profile': typeof StoreProfileRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/products': typeof ProductsIndexRoute
  '/stores': typeof StoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/terms': typeof TermsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/store/bookings': typeof StoreBookingsRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/store/products': typeof StoreProductsRoute
  '/store/profile': typeof StoreProfileRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/products/': typeof ProductsIndexRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/how-it-works'
    | '/privacy'
    | '/profile'
    | '/seller'
    | '/terms'
    | '/products/$productId'
    | '/store/bookings'
    | '/store/dashboard'
    | '/store/products'
    | '/store/profile'
    | '/stores/$storeId'
    | '/products/'
    | '/stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/how-it-works'
    | '/privacy'
    | '/profile'
    | '/seller'
    | '/terms'
    | '/products/$productId'
    | '/store/bookings'
    | '/store/dashboard'
    | '/store/products'
    | '/store/profile'
    | '/stores/$storeId'
    | '/products'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/dashboard'
    | '/how-it-works'
    | '/privacy'
    | '/profile'
    | '/seller'
    | '/terms'
    | '/products/$productId'
    | '/store/bookings'
    | '/store/dashboard'
    | '/store/products'
    | '/store/profile'
    | '/stores/$storeId'
    | '/products/'
    | '/stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SellerRoute: typeof SellerRoute
  TermsRoute: typeof TermsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  StoreBookingsRoute: typeof StoreBookingsRoute
  StoreDashboardRoute: typeof StoreDashboardRoute
  StoreProductsRoute: typeof StoreProductsRoute
  StoreProfileRoute: typeof StoreProfileRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/bookings': {
      id: '/store/bookings'
      path: '/store/bookings'
      fullPath: '/store/bookings'
      preLoaderRoute: typeof StoreBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/dashboard': {
      id: '/store/dashboard'
      path: '/store/dashboard'
      fullPath: '/store/dashboard'
      preLoaderRoute: typeof StoreDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/products': {
      id: '/store/products'
      path: '/store/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof StoreProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/profile': {
      id: '/store/profile'
      path: '/store/profile'
      fullPath: '/store/profile'
      preLoaderRoute: typeof StoreProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SellerRoute: SellerRoute,
  TermsRoute: TermsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  StoreBookingsRoute: StoreBookingsRoute,
  StoreDashboardRoute: StoreDashboardRoute,
  StoreProductsRoute: StoreProductsRoute,
  StoreProfileRoute: StoreProfileRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
